### Register a new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "userN": "john_doe",
    "password": "secretpassword123"
}

### Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "userN": "john_doe",
    "password": "secretpassword123"
}
### Get all products
GET http://localhost:3000/products
GET http://localhost:3000/users/1775384003686/basket

POST http://localhost:3000/users/1775384003686/basket
Content-Type: application/json

{
    "id": "prod_001",
    "name": "Mechanical Keyboard",
    "price": 89.99,
    "quantity": 1
}

PATCH http://localhost:3000/users/1775384003686/basket/prod_001
Content-Type: application/json

{
    "quantity": 5
}

DELETE http://localhost:3000/users/1775384003686/basket/prod_001

DELETE http://localhost:3000/users/1775384003686/basket