### Register a new user
POST https://localhost:3000/users
Content-Type: application/json

{
    "userN": "john_doe",
    "password": "secretpassword123"
}

### Login
POST https://localhost:3000/users/login
Content-Type: application/json

{
    "userN": "john_doe",
    "password": "secretpassword123"
}

### Get all products
GET https://localhost:3000/product

### Add item to basket
POST https://localhost:3000/users/1775805911738/basket
Content-Type: application/json

{
    "id": "prod_001",
    "name": "Mechanical Keyboard",
    "price": 89.99,
    "quantity": 1
}

### Get basket
GET https://localhost:3000/users/1775805911738/basket

### Update basket item quantity (user 1775805911738)
PATCH https://localhost:3000/users/1775805911738/basket/prod_001
Content-Type: application/json

{
    "quantity": 5
}


### Delete basket item (user 1775805911738)
DELETE https://localhost:3000/users/1775805911738/basket/prod_001

### Clear entire basket (user 1775805911738)
DELETE https://localhost:3000/users/1775805911738/basket